routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'language'], function () {
    
    // home page
    Route::get('/', 'LayoutController@index')->name('home_page');

    // auth routes
    Auth::routes(['verify' => true]);

    // only authorized users can access these routes, admin routes
    Route::group([
        'prefix' => 'admin', 
        'as' => 'admin.', 
        'middleware' => ['auth', 'verified', 'is_worker'], 
        'namespace' => 'Admin'], 
        function () {

        //    invoices routes
        Route::group(['prefix' => 'invoices', 'as' => 'invoices.'], function () {
            Route::get('/', InvoicesController::class.'@index')->name('index');
            Route::get('/{id}/generate', InvoicesController::class.'@store')->name('store');
            Route::get('/{id}/show', InvoicesController::class.'@show')->name('show');
            Route::delete('/{id}/delete', InvoicesController::class.'@destroy')->name('delete');
        });

        //    products routes
        Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
            Route::get('/', ProductsController::class.'@index')->name('index');
            Route::get('/create', ProductsController::class.'@create')->name('create');
            Route::get('/{id}/edit', ProductsController::class.'@edit')->name('edit');
            Route::delete('/{id}/delete', ProductsController::class.'@destroy')->name('delete');
            Route::post('/store', ProductsController::class.'@store')->name('save');

            //      products photos routes
            Route::group(['prefix' => 'photos', 'as' => 'photos.'], function () {
                Route::get('/{id}', ProductPhotosController::class.'@index')->name('index');
                Route::post('/{id}/store', ProductPhotosController::class.'@store')->name('save');
                Route::put('/{id}/update/{photo_id}', ProductPhotosController::class.'@update')->name('update');
                Route::get('/{id}/create', ProductPhotosController::class.'@create')->name('create');
                Route::get('/{id}/edit/{photo_id}', ProductPhotosController::class.'@edit')->name('edit')
                    ->where('photo_id', '[0-9]+');
                Route::delete('/{id}/delete/{photo_id}', ProductPhotosController::class.'@destroy')->name('delete')
                    ->where('photo_id', '[0-9]+');
                Route::post('/{id}/change-order', ProductPhotosController::class.'@changeOrder')->name('order');
            });

            //      products quantities routes
            Route::group(['prefix' => 'quantity', 'as' => 'quantity.'], function () {
                Route::get('/{id}', QuantitiesController::class.'@show')->name('show');
                Route::post('/{id}/store', QuantitiesController::class.'@store')->name('save');
            });
        });

        //    categories routes
        Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
            Route::get('/', CategoriesController::class.'@index')->name('index');
            Route::get('/create', CategoriesController::class.'@create')->name('create');
            Route::get('/{id}/edit', CategoriesController::class.'@edit')->name('edit');
            Route::post('/store', CategoriesController::class.'@store')->name('save');
            Route::put('/{id}/update', CategoriesController::class.'@update')->name('update');
            Route::delete('/{id}/delete', CategoriesController::class.'@destroy')->name('delete');
            Route::post('/{id}/show-subcategories', CategoriesController::class.'@showSubcategories')->name('show_subcategories');
        });

        //    orders routes
        Route::group(['prefix' => 'orders', 'as' => 'orders.'], function () {
            Route::get('/', OrdersController::class.'@index')->name('index');
            Route::get('/{id}/edit', OrdersController::class.'@edit')->name('edit');
            Route::post('/store', OrdersController::class.'@store')->name('save');
            Route::delete('/{id}/delete', OrdersController::class.'@destroy')->name('delete');
        });

        //    deliveries routes
        Route::group(['prefix' => 'deliveries', 'as' => 'deliveries.'], function () {
            Route::get('/', DeliveriesController::class.'@index')->name('index');
            Route::get('/create', DeliveriesController::class.'@create')->name('create');
            Route::get('/{id}/edit', DeliveriesController::class.'@edit')->name('edit');
            Route::post('/store', DeliveriesController::class.'@store')->name('save');
            Route::delete('/{id}/delete', DeliveriesController::class.'@destroy')->name('delete');
            Route::post('/change-order', DeliveriesController::class.'@changeOrder')->name('order');
        });

        //    payments routes
        Route::group(['prefix' => 'payments', 'as' => 'payments.'], function () {
            Route::get('/', PaymentsController::class.'@index')->name('index');
            Route::get('/create', PaymentsController::class.'@create')->name('create');
            Route::get('/{id}/edit', PaymentsController::class.'@edit')->name('edit');
            Route::post('/store', PaymentsController::class.'@store')->name('save');
            Route::delete('/{id}/delete', PaymentsController::class.'@destroy')->name('delete');
            Route::post('/change-order', PaymentsController::class.'@changeOrder')->name('order');
        });

        //    sizes routes
        Route::group(['prefix' => 'sizes', 'as' => 'sizes.'], function () {
            Route::get('/', SizesController::class.'@index')->name('index');
            Route::get('/create', SizesController::class.'@create')->name('create');
            Route::get('/{id}/edit', SizesController::class.'@edit')->name('edit');
            Route::post('/store', SizesController::class.'@store')->name('save');
            Route::delete('/{id}/delete', SizesController::class.'@destroy')->name('delete');
        });

        //    statuses routes
        Route::group(['prefix' => 'statuses', 'as' => 'statuses.'], function () {
            Route::get('/', StatusesController::class.'@index')->name('index');
            Route::get('/create', StatusesController::class.'@create')->name('create');
            Route::get('/{id}/edit', StatusesController::class.'@edit')->name('edit');
            Route::post('/store', StatusesController::class.'@store')->name('save');
            Route::delete('/{id}/delete', StatusesController::class.'@destroy')->name('delete');
        });

        //    users routes
        Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
            Route::get('/', UsersController::class.'@index')->name('index');
            Route::get('/create', UsersController::class.'@create')->name('create');
            Route::get('/{id}/edit', UsersController::class.'@edit')->name('edit');
            Route::post('/store', UsersController::class.'@store')->name('save');
            Route::delete('/{id}/delete', UsersController::class.'@destroy')->name('delete');
        });

        //    languages routes
        Route::group(['prefix' => 'languages', 'as' => 'languages.'], function () {
            Route::get('/', LanguagesController::class.'@index')->name('index');
            Route::get('/create', LanguagesController::class.'@create')->name('create');
            Route::get('/{id}/edit', LanguagesController::class.'@edit')->name('edit');
            Route::post('/store', LanguagesController::class.'@store')->name('save');
            Route::delete('/{id}/delete', LanguagesController::class.'@destroy')->name('delete');
            Route::put('/{id}/update', LanguagesController::class.'@update')->name('update');
        });

        //    pages routes
        Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {
            Route::get('/', PagesController::class.'@index')->name('index');

            //  slider routes
            Route::group(['prefix' => '/{id}/slider/{slider_id}', 'as' => 'slider.'], function () {
                Route::get('/', SliderController::class.'@index')->name('index');

                //  slider images
                Route::group(['prefix' => '/photos', 'as' => 'photos.'], function () {
                    Route::get('/create', SliderController::class.'@create')->name('create');
                    Route::get('/edit/{photo_id}', SliderController::class.'@edit')->name('edit')
                        ->where('photo_id', '[0-9]+');
                    Route::post('/store', SliderController::class.'@store')->name('save');
                    Route::put('/update/{photo_id}', SliderController::class.'@update')->name('update');
                    Route::delete('/delete/{photo_id}', SliderController::class.'@destroy')->name('delete')
                        ->where('photo_id', '[0-9]+');
                    Route::post('/change-order', SliderController::class.'@changeOrder')->name('order');
                });
            });

            //  wysiwyg routes
            Route::group(['prefix' => '/{id}/wysiwyg', 'as' => 'wysiwyg.'], function () {
                Route::get('/{wysiwyg_id}', PagesController::class.'@wysiwyg')->name('index')->where('wysiwyg_id', '[0-9]+');
                Route::put('/{wysiwyg_id}/update', PagesController::class.'@updateWysiwyg')->name('update')->where('wysiwyg_id', '[0-9]+');
            });
        });

        //    favicon routes
        Route::group(['prefix' => 'favicon', 'as' => 'favicon.'], function () {
            Route::get('/', FaviconController::class.'@edit')->name('edit');

app/Language.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

class Language extends Model
{
    protected $table = 'languages';

    protected $fillable = [
        'name',
        'native_name',
        'shortcut',
        'active',
        'main'
    ];
    
    public function currency() {
        return $this->belongsTo('App\CurrencyTranslation');
    }
    
    public function productPhoto() {
        return $this->belongsTo('App\ProductPhotoTranslation');
    }
    
    public function productSize() {
        return $this->belongsTo('App\SizeTranslation');
    }
    
    public function product() {
        return $this->belongsTo('App\ProductTranslation');
    }

    public static function getMain() {
        if (Cache::has('main_language')) {
            $language = Cache::get('main_language');
        }
        else{
            $language = Language::where('main', 1)->first();
            Cache::put('main_language', $language);
        }

        return $language;
    }

    public static function getLanguage() {
        if (Cache::has('language')) {
            $language = Cache::get('language');
        }
        elseif(session()->has('language')){
            $language = Language::select(['id', 'shortcut'])->where('id', session('language'))->first();
            Cache::put('language', $language);
        }
        else{
            $language = Language::select(['id', 'shortcut'])->where('main', 1)->first();
            Cache::put('language', $language);
        }

        return $language;
    }

    /**
     * Scope a query to only include active languages.
     *
     * @param $query
     * @return mixed
     */
    public function scopeActive($query): Builder
    {
        return $query->where('active', 1);
    }
}

app/Http/Controllers/Admin/LanguagesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\LanguageRequest;
use App\Language;
use App\LanguageTranslation;
use App\Http\Controllers\Controller;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class LanguagesController extends Controller
{
    /**
     * @param Request $request
     * @return View
     */
    public function index(Request $request): View
    {
        return view('admin.languages.index', [
            'languages' => Language::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        return view('admin.languages.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param LanguageRequest $request
     * @return RedirectResponse
     */
    public function store(LanguageRequest $request): RedirectResponse
    {
        $language = new Language();
        $language->name = $request->post('name');
        $language->native_name = $request->post('native_name');
        $language->shortcut = $request->post('shortcut');
        $language->active = $request->post('active') ? 1 : 0;
        $language->save();

        return redirect()->route('admin.languages.index')->with('message', trans('admin.saved_changes'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $id
     * @return View
     */
    public function edit($id): View
    {
        $language = Language::find($id);

        return view('admin.languages.edit', [
            'language' => $language
        ]);
    }

    /**
     * @param $id
     * @param LanguageRequest $request
     * @return RedirectResponse
     */
    public function update($id, LanguageRequest $request): RedirectResponse
    {
        $language = Language::findOrFail($id);
        $language->name = $request->post('name');
        $language->native_name = $request->post('native_name');
        $language->shortcut = $request->post('shortcut');
        $language->active = $request->post('active') ? 1 : 0;
        $language->save();

        return redirect()->route('admin.languages.index')->with('message', trans('admin.saved_changes'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $id
     * @return RedirectResponse
     */
    public function destroy($id): RedirectResponse
    {
        $language = Language::findOrFail($id);
        $language->delete();

        return redirect()->route('admin.languages.index')->with('message', trans('admin.deleted'));
    }
}

app/Http/Controllers/LanguagesController.php
<?php

namespace App\Http\Controllers;

use App\Language;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\App;

class LanguagesController extends Controller
{    
    /**
     * Changes language.
     * 
     * @param Request $request
     * @return type
     */
    public function changeLanguage(Request $request) {
        $language = Language::findOrFail(request()->language);
        Session::put('language', request()->language);
        App::setLocale($language->shortcut);
        Cache::put('language', $language);
        return redirect()->back();
    }
}

resources/views/admin/languages/create.blade.php
@extends('layouts.app')

@section('admin_style')
    <link rel="stylesheet" href="{{ asset('css/admin/admin.css') }}">
@endsection

@section('content')

<div class="container">

{{--    <div class="error" style="padding: 15px 0 0 15px;">{!! implode('', $errors->all('<p>:message</p>')) !!}</div>--}}

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">@lang('admin.fill_all')</h3>
                </div>
                <div class="panel-body">
                    <form name="save_language" method="post" action="{{ route('admin.languages.save') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <fieldset>
                            <div class="form-group">
                                <span class="@if($errors->has('name')) error @endif">
                                    {{ $errors->first('name') }}
                                </span>
                                <input class="form-control @if($errors->has('name')) error-input @endif"
                                       placeholder="@lang('admin.name')"
                                       name="name"
                                       type="text"
                                       value="{{ old('name') ?? '' }}"
                                       required maxlength="191">
                            </div>
                            <div class="form-group">
                                <span class="@if($errors->has('native_name')) error @endif">
                                    {{ $errors->first('native_name') }}
                                </span>
                                <input class="form-control @if($errors->has('native_name')) error-input @endif"
                                       placeholder="@lang('admin.native_name')"
                                       name="native_name"
                                       type="text"
                                       value="{{ old('native_name') ?? '' }}"
                                       required maxlength="191">
                            </div>
                            <div class="form-group">
                                <span class="@if($errors->has('shortcut')) error @endif">
                                    {{ $errors->first('shortcut') }}
                                </span>
                                <input class="form-control @if($errors->has('shortcut')) error-input @endif"
                                       placeholder="@lang('admin.shortcut')"
                                       name="shortcut"
                                       type="text"
                                       value="{{ old('shortcut') ?? '' }}"
                                       required maxlength="2" minlength="2">
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input name="active"
                                           type="checkbox"
                                            {{ (! empty(old('active')) ? 'checked' : '') }}
                                    >@lang('admin.active')
                                </label>
                            </div>
                            <input class="btn btn-lg btn-success btn-block" type="submit" value="@lang('admin.save')">
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/languages/edit.blade.php
@extends('layouts.app')

@section('admin_style')
    <link rel="stylesheet" href="{{ asset('css/admin/admin.css') }}">
@endsection

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">@lang('admin.fill_all')</h3>
                </div>
                <div class="panel-body">
                    <form name="save_language" method="post" action="{{ route('admin.languages.update', ['id' => $language->id]) }}" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <fieldset>
                            <div class="form-group">
                                <span class="@if($errors->has('name')) error @endif">
                                    {{ $errors->first('name') }}
                                </span>
                                <input class="form-control @if($errors->has('name')) error-input @endif"
                                       placeholder="@lang('admin.name')"
                                       name="name"
                                       type="text"
                                       value="{{ old('name') ?? $language->name }}"
                                       required maxlength="191">
                            </div>
                            <div class="form-group">
                                <span class="@if($errors->has('native_name')) error @endif">
                                    {{ $errors->first('native_name') }}
                                </span>
                                <input class="form-control @if($errors->has('native_name')) error-input @endif"
                                       placeholder="@lang('admin.native_name')"
                                       name="native_name"
                                       type="text"
                                       value="{{ old('native_name') ?? $language->native_name }}"
                                       required maxlength="191">
                            </div>
                            <div class="form-group">
                                <span class="@if($errors->has('shortcut')) error @endif">
                                    {{ $errors->first('shortcut') }}
                                </span>
                                <input class="form-control @if($errors->has('shortcut')) error-input @endif"
                                       placeholder="@lang('admin.shortcut')"
                                       name="shortcut"
                                       type="text"
                                       value="{{ old('shortcut') ?? $language->shortcut }}"
                                       required maxlength="2" minlength="2">
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input name="active"
                                           type="checkbox"
                                            {{ (! empty(old('active')) || $language->active ? 'checked' : '') }}
                                    >@lang('admin.active')
                                </label>
                            </div>
                            <input class="btn btn-lg btn-success btn-block" type="submit" value="@lang('admin.save')">
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/languages/index.blade.php
@extends('layouts.app')

@section('scripts')
    <script src="{{ asset('js/admin/modals/delete.js') }}"></script>
@endsection

@section('admin_style')
    <link rel="stylesheet" href="{{ asset('css/admin/admin.css') }}">
@endsection

@section('content')

@include('admin.modals.delete')

<div class="container">
    @if (session('message'))
        <div class="alert alert-info">{{ session('message') }}</div>
    @endif
    <a class="btn btn-primary" href="{{ route('admin.languages.create') }}" role="button">@lang('admin.add_new')</a>
    <div class="container">
        <div class="row header_row">
            <div class="col-xs-12 col-sm-6 col-md-2">
                <p>@lang('admin.name')</p>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-2">
                <p>@lang('admin.native_name')</p>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-2">
                <p>@lang('admin.shortcut')</p>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-2">
                <p>@lang('admin.flag')</p>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-2">
                <p>@lang('admin.active')</p>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-2">
                
            </div>
        </div>
        @include('admin.languages.row')
    </div>
</div>

@endsection

resources/views/admin/languages/row.blade.php
@foreach($languages as $language)
    <div class="row" id="language_{{ $language->id }}" style="@if($language->main) font-weight: bold; @endif">
        <div class="col-xs-12 col-sm-6 col-md-2">
            {{ $language->name }}
        </div>
        <div class="col-xs-12 col-sm-6 col-md-2">
            {{ $language->native_name }}
        </div>
        <div class="col-xs-12 col-sm-6 col-md-2">
            {{ $language->shortcut }}
        </div>
        <div class="col-xs-12 col-sm-6 col-md-2">
            <img src="{{ asset('images/flags/'.$language->shortcut.'.png') }}"
                 alt="{{ $language->name }}" class="miniature" />
        </div>
        <div class="col-xs-12 col-sm-6 col-md-2">
            @if($language->active)
                @lang('admin.yes')
            @else
                @lang('admin.no')
            @endif
        </div>
        <div class="col-xs-12 col-sm-6 col-md-2">
            <a href="{{ route('admin.languages.edit', ['id' => $language->id]) }}" title="@lang('admin.edit')">
                <i class="admin_fa far fa-edit fa-2x"></i>
            </a>
            <a href="{{ route('admin.languages.delete', ['id' => $language->id]) }}"
               title="@lang('admin.delete')" class="delete_item">
                <i class="admin_fa far fa-trash-alt fa-2x"></i>
            </a>
        </div>
    </div>
@endforeach