routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'language'], function () {
    
    // home page
    Route::get('/', 'LayoutController@index')->name('home_page');

    // auth routes
    Auth::routes(['verify' => true]);

    // only authorized users can access these routes, admin routes
    Route::group([
        'prefix' => 'admin', 
        'as' => 'admin.', 
        'middleware' => ['auth', 'verified', 'is_worker'], 
        'namespace' => 'Admin'], 
        function () {

        //    invoices routes
        Route::group(['prefix' => 'invoices', 'as' => 'invoices.'], function () {
            Route::get('/', InvoicesController::class.'@index')->name('index');
            Route::get('/{id}/generate', InvoicesController::class.'@store')->name('store');
            Route::get('/{id}/show', InvoicesController::class.'@show')->name('show');
            Route::delete('/{id}/delete', InvoicesController::class.'@destroy')->name('delete');
        });

        //    products routes
        Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
            Route::get('/', ProductsController::class.'@index')->name('index');
            Route::get('/create', ProductsController::class.'@create')->name('create');
            Route::get('/{id}/edit', ProductsController::class.'@edit')->name('edit');
            Route::delete('/{id}/delete', ProductsController::class.'@destroy')->name('delete');
            Route::post('/store', ProductsController::class.'@store')->name('save');

            //      products photos routes
            Route::group(['prefix' => 'photos', 'as' => 'photos.'], function () {
                Route::get('/{id}', ProductPhotosController::class.'@index')->name('index');
                Route::post('/{id}/store', ProductPhotosController::class.'@store')->name('save');
                Route::put('/{id}/update/{photo_id}', ProductPhotosController::class.'@update')->name('update');
                Route::get('/{id}/create', ProductPhotosController::class.'@create')->name('create');
                Route::get('/{id}/edit/{photo_id}', ProductPhotosController::class.'@edit')->name('edit')
                    ->where('photo_id', '[0-9]+');
                Route::delete('/{id}/delete/{photo_id}', ProductPhotosController::class.'@destroy')->name('delete')
                    ->where('photo_id', '[0-9]+');
                Route::post('/{id}/change-order', ProductPhotosController::class.'@changeOrder')->name('order');
            });

            //      products quantities routes
            Route::group(['prefix' => 'quantity', 'as' => 'quantity.'], function () {
                Route::get('/{id}', QuantitiesController::class.'@show')->name('show');
                Route::post('/{id}/store', QuantitiesController::class.'@store')->name('save');
            });
        });

        //    categories routes
        Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
            Route::get('/', CategoriesController::class.'@index')->name('index');
            Route::get('/create', CategoriesController::class.'@create')->name('create');
            Route::get('/{id}/edit', CategoriesController::class.'@edit')->name('edit');
            Route::post('/store', CategoriesController::class.'@store')->name('save');
            Route::put('/{id}/update', CategoriesController::class.'@update')->name('update');
            Route::delete('/{id}/delete', CategoriesController::class.'@destroy')->name('delete');
            Route::post('/{id}/show-subcategories', CategoriesController::class.'@showSubcategories')->name('show_subcategories');
        });

        //    orders routes
        Route::group(['prefix' => 'orders', 'as' => 'orders.'], function () {
            Route::get('/', OrdersController::class.'@index')->name('index');
            Route::get('/{id}/edit', OrdersController::class.'@edit')->name('edit');
            Route::post('/store', OrdersController::class.'@store')->name('save');
            Route::delete('/{id}/delete', OrdersController::class.'@destroy')->name('delete');
        });

        //    deliveries routes
        Route::group(['prefix' => 'deliveries', 'as' => 'deliveries.'], function () {
            Route::get('/', DeliveriesController::class.'@index')->name('index');
            Route::get('/create', DeliveriesController::class.'@create')->name('create');
            Route::get('/{id}/edit', DeliveriesController::class.'@edit')->name('edit');
            Route::post('/store', DeliveriesController::class.'@store')->name('save');
            Route::delete('/{id}/delete', DeliveriesController::class.'@destroy')->name('delete');
            Route::post('/change-order', DeliveriesController::class.'@changeOrder')->name('order');
        });

        //    payments routes
        Route::group(['prefix' => 'payments', 'as' => 'payments.'], function () {
            Route::get('/', PaymentsController::class.'@index')->name('index');
            Route::get('/create', PaymentsController::class.'@create')->name('create');
            Route::get('/{id}/edit', PaymentsController::class.'@edit')->name('edit');
            Route::post('/store', PaymentsController::class.'@store')->name('save');
            Route::delete('/{id}/delete', PaymentsController::class.'@destroy')->name('delete');
            Route::post('/change-order', PaymentsController::class.'@changeOrder')->name('order');
        });

        //    sizes routes
        Route::group(['prefix' => 'sizes', 'as' => 'sizes.'], function () {
            Route::get('/', SizesController::class.'@index')->name('index');
            Route::get('/create', SizesController::class.'@create')->name('create');
            Route::get('/{id}/edit', SizesController::class.'@edit')->name('edit');
            Route::post('/store', SizesController::class.'@store')->name('save');
            Route::delete('/{id}/delete', SizesController::class.'@destroy')->name('delete');
        });

        //    statuses routes
        Route::group(['prefix' => 'statuses', 'as' => 'statuses.'], function () {
            Route::get('/', StatusesController::class.'@index')->name('index');
            Route::get('/create', StatusesController::class.'@create')->name('create');
            Route::get('/{id}/edit', StatusesController::class.'@edit')->name('edit');
            Route::post('/store', StatusesController::class.'@store')->name('save');
            Route::delete('/{id}/delete', StatusesController::class.'@destroy')->name('delete');
        });

        //    users routes
        Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
            Route::get('/', UsersController::class.'@index')->name('index');
            Route::get('/create', UsersController::class.'@create')->name('create');
            Route::get('/{id}/edit', UsersController::class.'@edit')->name('edit');
            Route::post('/store', UsersController::class.'@store')->name('save');
            Route::delete('/{id}/delete', UsersController::class.'@destroy')->name('delete');
        });

        //    languages routes
        Route::group(['prefix' => 'languages', 'as' => 'languages.'], function () {
            Route::get('/', LanguagesController::class.'@index')->name('index');
            Route::get('/create', LanguagesController::class.'@create')->name('create');
            Route::get('/{id}/edit', LanguagesController::class.'@edit')->name('edit');
            Route::post('/store', LanguagesController::class.'@store')->name('save');
            Route::delete('/{id}/delete', LanguagesController::class.'@destroy')->name('delete');
            Route::put('/{id}/update', LanguagesController::class.'@update')->name('update');
        });

        //    pages routes
        Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {
            Route::get('/', PagesController::class.'@index')->name('index');

            //  slider routes
            Route::group(['prefix' => '/{id}/slider/{slider_id}', 'as' => 'slider.'], function () {
                Route::get('/', SliderController::class.'@index')->name('index');

                //  slider images
                Route::group(['prefix' => '/photos', 'as' => 'photos.'], function () {
                    Route::get('/create', SliderController::class.'@create')->name('create');
                    Route::get('/edit/{photo_id}', SliderController::class.'@edit')->name('edit')
                        ->where('photo_id', '[0-9]+');
                    Route::post('/store', SliderController::class.'@store')->name('save');
                    Route::put('/update/{photo_id}', SliderController::class.'@update')->name('update');
                    Route::delete('/delete/{photo_id}', SliderController::class.'@destroy')->name('delete')
                        ->where('photo_id', '[0-9]+');
                    Route::post('/change-order', SliderController::class.'@changeOrder')->name('order');
                });
            });

            //  wysiwyg routes
            Route::group(['prefix' => '/{id}/wysiwyg', 'as' => 'wysiwyg.'], function () {
                Route::get('/{wysiwyg_id}', PagesController::class.'@wysiwyg')->name('index')->where('wysiwyg_id', '[0-9]+');
                Route::put('/{wysiwyg_id}/update', PagesController::class.'@updateWysiwyg')->name('update')->where('wysiwyg_id', '[0-9]+');
            });
        });

        //    favicon routes
        Route::group(['prefix' => 'favicon', 'as' => 'favicon.'], function () {
            Route::get('/', FaviconController::class.'@edit')->name('edit');

app/ProductPhoto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Language;
use Illuminate\Support\Facades\File;

class ProductPhoto extends Model
{
    protected $table = 'product_photos';

    protected $fillable = [
        'product_id',
        'photo',
        'sequence'
    ];

    public static $photo_width = 480;
    public static $photo_height = 640;
    public static $ratio_height = 4;
    public static $ratio_width = 3;
    public static $keep_original = false;

    /**
     * relation to product
     * @return type
     */
    public function product() {
        return $this->belongsTo('App\Product');
    }
    
    /**
     * photo translations
     * @return type
     */
    public function translation() {
        return $this->hasMany('App\ProductPhotoTranslation');
    }
    
    /**
     * get photo data in selected language
     * @param type $language_id
     * @return type
     */
    public function getData($language_id = false) {
        $language = Language::getMain();
        if(!$language_id){
            $language_id = session()->has('language') ? session('language') : $language->id;
        }
        
        if($language_id == $language->id){
            return $this->translation->where('language_id', $language_id)->first();
        }
        else{
            if($this->translation->where('language_id', $language_id)->count() > 0){
                return $this->translation->where('language_id', $language_id)->first();
            }
            else{
                return $this->translation->where('language_id', $language->id)->first();
            }
        }
    }
    
    /**
     * removes photos
     */
    public function removePhotos() {
        if($this->photo){
            $base_path = 'app' . DIRECTORY_SEPARATOR . 'public' . DIRECTORY_SEPARATOR . 'images' .
                DIRECTORY_SEPARATOR . 'products' . DIRECTORY_SEPARATOR . $this->product_id . DIRECTORY_SEPARATOR;
            $image_path = storage_path($base_path . ProductPhoto::$photo_width . 'x' . ProductPhoto::$photo_height . DIRECTORY_SEPARATOR . $this->photo);
            $original_image_path = storage_path($base_path . 'original' . DIRECTORY_SEPARATOR . $this->photo);

            $files = array($image_path, $original_image_path);

            foreach ($files as $file) {
                File::delete($file);
            }
            
            $this->photo = null;
        }
    }
}

resources/views/admin/productPhotos/create.blade.php
@extends('layouts.app')

@section('admin_style')
    <link rel="stylesheet" href="{{ asset('css/admin/admin.css') }}">
@endsection

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">@lang('admin.fill_all')</h3>
                    </div>
                    <div class="error" style="padding: 15px 0 0 15px;">{!! implode('', $errors->all('<p>:message</p>')) !!}</div>
                    <div class="panel-body">
                        <form name="product_photo_save" method="post" action="{{ route('admin.products.photos.save', ['id' => $product->id]) }}" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            @include('admin.cropper.dropzone', [
                                'photoConfig' => $photoConfig,
                                'maxFileSize' => 2,
                                'maxFiles' => 5,
                                'paramName' => 'file',
                                'acceptedFiles' => 'image/jpeg'
                            ])
                            <fieldset>
                                @foreach($languages as $language)
                                    <div>
                                        <img src="{{ asset('images/flags/'.$language->shortcut).'.png' }}" 
                                                        alt="{{ $language->name }}" />
                                        <p class="language_name">{{ ucfirst($language->name) }}</p>
                                    </div>
                                    <div class="form-group">
                                        <span class="@if(session()->has('error_data.name.'.$language->id)) error @endif">
                                            @if(session()->has('error_data.name.'.$language->id))
                                                {{ session('error_data.name.'.$language->id) }}
                                            @endif
                                        </span>
                                        <input class="form-control @if(session()->has('error_data.name.'.$language->id)) error-input @endif" 
                                               placeholder="@lang('admin.name') ({{ $language->shortcut }})" 
                                               name="name[{{ $language->id }}]" 
                                               type="text" 
                                               value="{{ old('name.'.$language->id) }}"
                                               required>
                                    </div>
                                @endforeach
                                <div class="form-group">
                                    <div class="col-sm-6">
                                        <span>@lang('admin.photo'):</span>
                                        @if ($errors->has('photo'))
                                            <span class=error">
                                                {{ $errors->first('photo') }}
                                            </span>
                                        @endif
                                    </div>
                                    <div class="col-sm-6">
                                    </div>
                                </div>
                                <input class="btn btn-lg btn-success btn-block" type="submit" value="@lang('admin.save')">
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/productPhotos/edit.blade.php
@extends('layouts.app')

@section('admin_style')
    <link rel="stylesheet" href="{{ asset('css/admin/admin.css') }}">
@endsection

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">@lang('admin.fill_all')</h3>
                    </div>
                    <div class="error" style="padding: 15px 0 0 15px;">{!! implode('', $errors->all('<p>:message</p>')) !!}</div>
                    <div class="panel-body">
                        <form name="product_photo_save" method="post" action="{{ route('admin.products.photos.update',
                            ['id' => $product->id, 'photo_id' => $product_photo->id]) }}" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}
                            @include('admin.cropper.dropzone', [
                                'photoConfig' => $photoConfig,
                                'maxFileSize' => 2,
                                'maxFiles' => 1,
                                'paramName' => 'file',
                                'acceptedFiles' => 'image/jpeg'
                            ])
                            <fieldset>
                                @foreach($languages as $language)
                                    <div>
                                        <img src="{{ asset('images/flags/'.$language->shortcut).'.png' }}" 
                                                        alt="{{ $language->name }}" />
                                        <p class="language_name">{{ ucfirst($language->name) }}</p>
                                    </div>
                                    <div class="form-group">
                                        <span class="@if(session()->has('error_data.name.'.$language->id)) error @endif">
                                            @if(session()->has('error_data.name.'.$language->id))
                                                {{ session('error_data.name.'.$language->id) }}
                                            @endif
                                        </span>
                                        <input class="form-control @if(session()->has('error_data.name.'.$language->id)) error-input @endif" 
                                               placeholder="@lang('admin.name') ({{ $language->shortcut }})" 
                                               name="name[{{ $language->id }}]" 
                                               type="text" 
                                               value="{{ old('name.'.$language->id, $product_photo->getData($language->id)->name ?? '') }}"
                                               required>
                                    </div>
                                @endforeach
                                <div class="form-group">
                                    <div class="col-sm-12">
                                        <span>@lang('admin.photo'):</span>
                                        @if ($errors->has('photo'))
                                            <span class=error">
                                                {{ $errors->first('photo') }}
                                            </span>
                                        @endif
                                        <img src="{{ asset('storage/images/products/' . $product->id . '/' .
                                        $photoConfig['width'] . 'x' . $photoConfig['height'] . '/' . $product_photo->photo) }}"
                                            alt="{{ $product_photo->getData()->name }}" class="miniature" />
                                    </div>
                                </div>
                                <input class="btn btn-lg btn-success btn-block" type="submit" value="@lang('admin.save')">
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/productPhotos/index.blade.php
@extends('layouts.app')

@section('admin_style')
    <link rel="stylesheet" href="{{ asset('css/admin/admin.css') }}">
@endsection

@section('admin_scripts')
    <script src="{{ asset('plugins/Sortable.min.js') }}"></script>
    <script src="{{ asset('js/admin/productsPhotos.js') }}"></script>
    <script src="{{ asset('js/admin/modals/delete.js') }}"></script>
@endsection

@section('content')

@include('admin.modals.delete')

<input type="hidden" name="url_change_order" value="{{ route('admin.products.photos.order', ['id' => $product->id]) }}" />

<div class="container">
    @if (session('message'))
        <div class="alert alert-info">{{ session('message') }}</div>
    @endif
    <a class="btn btn-primary" href="{{ route('admin.products.index') }}" role="button">@lang('admin.back')</a>
    <a class="btn btn-primary" href="{{ route('admin.products.photos.create', ['id' => $product->id]) }}" role="button">@lang('admin.add_new')</a>

    <div id="sortable_div">
        @foreach($product->photos as $photo)
            <div class="sortable_element" draggable="false">
                <div class="sortable_handle">
                    <i class="fas fa-grip-horizontal"></i>
                    {{ $photo->getData()->name }}
                </div>
                <div>
                    @if($photo->photo)
                        <img src="{{ asset('storage/images/products/' . $product->id . '/' .
                            $photoConfig['width'] . 'x' . $photoConfig['height'] . '/' . $photo->photo) }}"
                             alt="{{ $photo->getData()->name }}" class="miniature" draggable="false"
                             data-sortable-id="{{ $loop->iteration }}" />
                    @endif
                </div>
                <div>
                    <a href="{{ route('admin.products.photos.edit', ['id' => $product->id, 'photo_id' => $photo->id]) }}" 
                       title="@lang('admin.edit')">
                        <i class="admin_fa far fa-edit fa-2x"></i>
                    </a>
                    <a href="{{ route('admin.products.photos.delete', ['id' => $product->id, 'photo_id' => $photo->id]) }}" 
                       title="@lang('admin.delete')" class="delete_item">
                        <i class="admin_fa far fa-trash-alt fa-2x"></i>
                    </a>
                </div>
            </div>
        @endforeach
    </div>
</div>
<input type="hidden" name="product_id" id="product_id" value="{{ $product->id }}" />
@endsection